'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.34209
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebMineMP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  &lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;ログイン&lt;/title&gt;
        '''    &lt;style&gt;
        '''        p#title {
        '''            background-color: lightblue;
        '''            color: blue;
        '''            text-align: center;
        '''            font-size: 30px;
        '''        }
        '''
        '''        p#alert {
        '''            color: red;
        '''            font-weight: bold;
        '''        }
        '''    &lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''    &lt;p id=&quot;title&quot;&gt;ログイン&lt;/p&gt;
        '''    &lt;form class=&quot;form&quot; action=&quot;login&quot;&gt;
        '''        &lt;p&gt;ユーザー名:&lt;input type=&quot;text&quot; class=&quot;form&quot; name=&quot;id&quot; /&gt;&lt;/p&gt;
        '''        &lt;p&gt;パスワード:&lt;input type=&quot;password&quot; cl [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Login() As String
            Get
                Return ResourceManager.GetString("Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;ログイン&lt;/title&gt;
        '''    &lt;style&gt;
        '''        p#title {
        '''            background-color: lightblue;
        '''            color: blue;
        '''            text-align: center;
        '''            font-size: 30px;
        '''        }
        '''
        '''        p#alert {
        '''            color: red;
        '''            font-weight: bold;
        '''        }
        '''    &lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''    &lt;p id=&quot;title&quot;&gt;ログイン&lt;/p&gt;
        '''    &lt;form class=&quot;form&quot; action=&quot;login&quot;&gt;
        '''        &lt;p id=&quot;alert&quot;&gt;不正なセッションです。&lt;/p&gt;
        '''        &lt;p&gt;ユーザー名:&lt;input type=&quot;text&quot; class=&quot;form&quot; name=&quot;id&quot; /&gt;&lt;/p&gt;
        '''    [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Login_InvalidSession() As String
            Get
                Return ResourceManager.GetString("Login_InvalidSession", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;ログイン&lt;/title&gt;
        '''    &lt;style&gt;
        '''        p#title {
        '''            background-color: lightblue;
        '''            color: blue;
        '''            text-align: center;
        '''            font-size: 30px;
        '''        }
        '''
        '''        p#alert {
        '''            color: red;
        '''            font-weight: bold;
        '''        }
        '''    &lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''    &lt;p id=&quot;title&quot;&gt;ログイン&lt;/p&gt;
        '''    &lt;form class=&quot;form&quot; action=&quot;login&quot;&gt;
        '''        &lt;p id=&quot;alert&quot;&gt;ユーザー名とパスワードの組み合わせが間違っています。&lt;/p&gt;
        '''        &lt;p&gt;ユーザー名:&lt;input type=&quot;text&quot; class=&quot;form&quot; name=&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Login_Wrong() As String
            Get
                Return ResourceManager.GetString("Login_Wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;メイン画面&lt;/title&gt;
        '''    &lt;style&gt;
        '''        #title {
        '''            background-color: lightblue;
        '''            color: blue;
        '''            text-align: center;
        '''            font-size: 30px;
        '''        }
        '''
        '''        #alert {
        '''            color: red;
        '''            font-weight: bold;
        '''        }
        '''
        '''        #main {
        '''        }
        '''
        '''        #tabs {
        '''            box-orient: horizontal;
        '''            display: -moz-box;
        '''            display: -webkit-box;
        '''            -moz-box-orient: horizontal;
        '''            -w [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Main_1() As String
            Get
                Return ResourceManager.GetString("Main_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;メイン画面&lt;/title&gt;
        '''    &lt;style&gt;
        '''        #title {
        '''            background-color: lightblue;
        '''            color: blue;
        '''            text-align: center;
        '''            font-size: 30px;
        '''        }
        '''
        '''        #alert {
        '''            color: red;
        '''            font-weight: bold;
        '''        }
        '''
        '''        #main {
        '''        }
        '''
        '''        #tabs {
        '''            box-orient: horizontal;
        '''            display: -moz-box;
        '''            display: -webkit-box;
        '''            -moz-box-orient: horizontal;
        '''            -w [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Main_2() As String
            Get
                Return ResourceManager.GetString("Main_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;メイン画面&lt;/title&gt;
        '''    &lt;style&gt;
        '''        #title {
        '''            background-color: lightblue;
        '''            color: blue;
        '''            text-align: center;
        '''            font-size: 30px;
        '''        }
        '''
        '''        #alert {
        '''            color: red;
        '''            font-weight: bold;
        '''        }
        '''
        '''        #main {
        '''        }
        '''
        '''        #tabs {
        '''            box-orient: horizontal;
        '''            display: -moz-box;
        '''            display: -webkit-box;
        '''            -moz-box-orient: horizontal;
        '''            -w [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Main_3() As String
            Get
                Return ResourceManager.GetString("Main_3", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
